### PR TITLE
feat: add a reporter showing the names of tests, both passing and failing

### PR DESCRIPTION
**Pull request by Augustin82**
elm-test-runner_console-with-names

### CODE REVIEW

**Comment by mpizenberg** [comment]
Nice one! I'm wondering do you think this is better suited for a completely different reporter as is done here with `"consoleFull"` or could it be activated by a verbosity level, like `elm-test-rs -v`?

Currently, verbosity levels only impact the `stderr` output, and not the `stdout` output, which is the report, but maybe the extra detail provided here could be provided when adding verbosity `-v`? What do you think?

**Comment by mpizenberg** [comment]
Or another possible option is to make custom reports a thing. I've thought a bit about that and I think it would be possible, with something like this:
```sh
elm-test-rs --report "custom" --report-package "user/package@1.0.0" --report-fn "MyReporter.implementation"
```
Since elm-test-rs can solve dependencies on the fly, it can add `user/package@1.0.0` to the dependencies to compile the reporter, and we can use something like this for the [`templates/Reporter.elm`](https://github.com/mpizenberg/elm-test-rs/blob/v2.0/templates/Reporter.elm) main compiled by elm-test-rs:
```elm
port module Reporter exposing (main)

import ElmTestRunner.Reporter exposing (Flags, Model, Msg)
import Json.Decode exposing (Value)
import {{ custom-reporter-module }}


port restart : ({ kind : String, testsCount : Int } -> msg) -> Sub msg
port incomingResult : ({ duration : Float, result : Value, logs : List String } -> msg) -> Sub msg
port signalFinished : { exitCode : Int, testsCount : Int } -> Cmd msg
port stdout : String -> Cmd msg


main : Program Flags Model Msg
main =
    ElmTestRunner.Reporter.customWorker {{ custom-reporter-fn }}
        { restart = restart
        , incomingResult = incomingResult
        , stdout = stdout
        , signalFinished = signalFinished
        }
``` 
Where the template values `{{ custom-reporter-module }}` and `{{ custom-reporter-fn }}` are replaced by `MyReporter` and `MyReporter.implementation`.

**Comment by mpizenberg** [comment]
Well we've had 20 voters and it seems the most popular answer is to use the `--verbose` flag (https://discourse.elm-lang.org/t/do-you-want-a-list-of-all-tests-passing-and-failing-in-your-console-test-reports/8249). So since it was also one of my two favorites we'll do that if that's ok with you.

Also, are you ok with the report taking the shape of a recap just above the final summary, to avoid mixing successful tests and failure details?

```txt
Running 2 tests. To reproduce these results later,
run elm-test-rs with --seed 558596839 and --fuzz 100

↓ Question
✗ wrong answer

    43
    ╷
    │ Expect.equal
    ╵
    42

Tests listing:

↓ Question
   ✗ wrong answer
   ✓ correct answer

TEST RUN FAILED

Duration: 3 ms
Passed:   1
Failed:   1
```

If you're ok with both, I can go ahead and update this PR

**Comment by Augustin82** [comment]
> If you're ok with both, I can go ahead and update this PR

I'm good! =)

**Comment by mpizenberg** [comment]
What do you think? One remark is that this feature cannot display tests that are marked with `skip` because it simply does not appear in the list of tests to run. The test runner is only aware of the fact that some tests are skipped.

image

**Pull request merged**
